os: windows
sudo: required

language: node_js

node_js:
  - '10'

addons:
  chrome: stable

env:
  - ci=travis

cache: node_modules

install:
  - npm install -g codecov
  - npm install

script:
  - npm run build
  - npm run unit:node
  - cat coverage/*/lcov.info | codecov
