version: "{build}"
init:
  - appveyor version
  - sh: echo "worker cloud: $APPVEYOR_BUILD_WORKER_CLOUD"
  - sh: echo "worker image: $APPVEYOR_BUILD_WORKER_IMAGE"
  
environment:
  nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

build: off
