version: "v1 - {build}"
image: Visual Studio 2015
init:
  - appveyor version
  - ps: echo worker cloud is $env:APPVEYOR_BUILD_WORKER_CLOUD
  - ps: echo worker image is $env:APPVEYOR_BUILD_WORKER_IMAGE
  - git config --global core.autocrlf input
  
environment:
  nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

build: off
