version: "{build}"
init:
  - appveyor version
  - echo "worker cloud is $env:APPVEYOR_BUILD_WORKER_CLOUD"
  - echo "worker image is $env:APPVEYOR_BUILD_WORKER_IMAGE"
  
environment:
  nodejs_version: '10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

build: off
