version: "v1 - {build}"
image: Visual Studio 2015

environment:
  ci: 'appveyor'
  nodejs_version: '10'
  npm_auth_token: ''

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

only_commits:
  files:
    - config/
    - src/
    - types/
    - .babelrc
    - .nycrc
    - tsconfig.json
    - rollup.config.js
    - mocha.opts
    - tslint.json
    - package.json
    - appveyor.yml

init:
  - appveyor version
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install -g coveralls
  - npm install

build_script:
  - npm run build

test_script:
  - npm run unit:node
  - npm run unit:browser -- --browsers IE8,IE9,Chrome --single-run

after_test:
  - cat coverage/*/lcov.info | coveralls

deploy_script:
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
