version: "v1 - {build}"
image: Visual Studio 2015
init:
  - appveyor version
  - ps: echo $env:APPVEYOR_BUILD_WORKER_CLOUD
  - ps: echo $env:APPVEYOR_BUILD_WORKER_IMAGE
  - git config --global core.autocrlf input
  
environment:
  nodejs_version: '10'
  ci: 'appveyor'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build
  
test_script:
  - node --version
  - npm --version
  - npm run unit:node
  - npm run unit:browser -- --browsers IE,Chrome --single-run

after_test:
  - cat coverage/*/lcov.info | codecov

